stages:
  - ci
  - unit test
  - build test
  # - notifications
  # - up test environment
  - e2e test
  - deployment
# - triggers

variables:
  CLI_VERSION: 10.1.6

build robot framework:
  stage: ci
  image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
  script:
    - docker-compose build --no-cache robotframework
    - docker-compose push robotframework
  only:
    refs:
      - develop
    changes:
      - dockerfiles/robotframework/robotframework/Dockerfile

unit test and lint:
  stage: unit test
  image: registryv2.zweicom.com:5000/trion/ng-cli-karma:${CLI_VERSION}
  script:
    - cd angular-project
    - npm ci
    - ng lint
    - ng test --code-coverage --progress false --watch false
  coverage: '/^Statements\s*:\s*([^%]+)/'

build a develop image for test:
  stage: build test
  image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
  script:
    - docker-compose -f docker-compose.yml build --no-cache develop
    - docker-compose -f docker-compose.yml push develop

e2e robotframework:
  stage: up test environment
  image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
  script:
    - docker-compose -f dockers-ambiente-local/docker-compose.yml down -v
    - docker-compose -f dockers-ambiente-local/docker-compose.yml build --no-cache mcl_otec_web mcl_robotframework
    - docker-compose -f dockers-ambiente-local/docker-compose.yml up -d mcl_otec_web
    - docker-compose -f dockers-ambiente-local/docker-compose.yml run mcl_robotframework
  after_script:
    - docker-compose -f dockers-ambiente-local/docker-compose.yml down -v

docker:
  stage: deployment
  image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
  script:
    - docker-compose -f docker-compose.yml build --no-cache deploy
    - docker-compose -f docker-compose.yml push deploy
  only:
    - tags
    - develop


    # demos_env:
#     image: registryv2.zweicom.com:5000/appropriate/curl
#     stage: notifications
#     script:
#         - |
#           curl -X POST \
#           -F "variables[ORIGIN]=$ORIGIN" \
#           -F "variables[CI_PIPELINE_ID]=$CI_PIPELINE_ID" \
#           -F "variables[PRECURSOR]=$CI_PROJECT_NAME" \
#           -F token=74396a440c70c392dabe7f01341bb0 \
#           -F ref=develop http://192.168.14.50/api/v4/projects/665/trigger/pipeline

# e2e robotframework:
#   stage: e2e test
#   image: registryv2.zweicom.com:5000/robotframework:latest
#   script:
#     - robot .

# e2e robotframework:
#   stage: e2e test
#   image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
#   script:
#     - cd dockers-ambiente-local
#     - docker-compose exec -T mcl_robotframework robot .