stages:
  - ci
  - deployment
  - build
# - triggers

variables:
  CLI_VERSION: 10.1.6

build robot framework:
  stage: ci
  image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
  script:
    - docker-compose build --no-cache robotframework
    - docker-compose push robotframework
  only:
    refs:
      - develop
    changes:
      - dockerfiles/robotframework/robotframework/Dockerfile
unit test and lint:
  stage: ci
  image: registryv2.zweicom.com:5000/trion/ng-cli-karma:${CLI_VERSION}
  script:
    - cd angular-project
    - npm ci
    - ng lint
    - ng test --code-coverage --progress false --watch false
  coverage: '/^Statements\s*:\s*([^%]+)/'

build a develop image for test:
  stage: ci
  image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
  script:
    - docker-compose -f docker-compose.yml build --no-cache develop
    - docker-compose -f docker-compose.yml push develop
  needs: ["unit test and lint"]

up ambiente test:
  stage: ci
  image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
  script:
    - cd dockers-ambiente-local
    - docker-compose up -d mcl_web_otec
  needs: ["build a develop image for test"]

robotframework:
  stage: ci
  image: registryv2.zweicom.com:5000/robotframework:latest
  script:
    - robot .
  needs: ["up ambiente test"]

docker:
  stage: deployment
  image: registryv2.zweicom.com:5000/tmaier/docker-compose:latest
  script:
    - docker-compose -f docker-compose.yml build --no-cache deploy
    - docker-compose -f docker-compose.yml push deploy
  only:
    - tags
    - develop
