stages:
  - linter
  - unit test
  - e2e test

variables:
  CLI_VERSION: 14.1.0
  GIT_STRATEGY: clone

.connect_gcr: &connect_gcr
  before_script:
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://gcr.io < ${HOME}/gcloud-service-key.json

linter:
  stage: linter
  image: trion/ng-cli-karma:${CLI_VERSION}
  script:
    - npm ci
    - ng lint

unit test:
  stage: unit test
  image: trion/ng-cli-karma:${CLI_VERSION}
  script:
    - npm ci
    - ng test --code-coverage --progress false --watch false
  coverage: '/^Statements\s*:\s*([^%]+)/'

e2e test:
  image: cypress/browsers:node16.5.0-chrome94-ff93
  stage: e2e test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm start & ./node_modules/.bin/wait-on http://localhost:4206
    # run Cypress tests
    - npx cypress run
