stages:
  - ci
  - unit test
  - e2e test
  - deployment
  - triggers

variables:
  CLI_VERSION: 10.1.6
  GIT_STRATEGY: clone

.connect_gcr: &connect_gcr
  before_script:
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://gcr.io < ${HOME}/gcloud-service-key.json

# unit test and lint:
#   stage: unit test
#   image: trion/ng-cli-karma:${CLI_VERSION}
#   script:
#     - cd angular-project
#     - npm ci
#     - ng lint
#     - ng test --code-coverage --progress false --watch false
#   coverage: '/^Statements\s*:\s*([^%]+)/'

e2e robotframework:
  stage: e2e test
  script:
    - docker-compose -f docker-compose.yml down -v
    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml build --no-cache mcl_test_sigo_web
    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml up -d --build mcl_test_sigo_web
    - docker -p ${CI_PIPELINE_ID} run --user $(id -u):$(id -g) -e ROBOT_OPTIONS="--exclude automatizacion --variable url:http://mcl_test_sigo_web --variable ambiente:testing" -v /tmp/reports:/opt/robotframework/reports:Z -v robot_e2e:/opt/robotframework/tests:Z ppodgorsek/robot-framework:latest

#e2e robotframework:
#  <<: *connect_gcr
#  stage: e2e test
#  image: juanpabloaj/docker-compose-google-cloud-sdk:latest
#  script:
#    - docker-compose -f docker-compose.yml down -v
#    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml pull mcl_test_sigo_db
#    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml pull mcl_test_sigo_api
#    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml build --no-cache mcl_e2e_robotframework mcl_test_sigo_web
#    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml up -d --build mcl_test_sigo_db mcl_test_sigo_api mcl_test_sigo_web
#    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml run dockerize-test-waiting
#    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml run mcl_e2e_robotframework
#  after_script:
#    - docker-compose -p ${CI_PIPELINE_ID} -f docker-compose.yml down -v
#  tags:
#    - docker_sigo

docker:
  <<: *connect_gcr
  stage: deployment
  image: juanpabloaj/docker-compose-google-cloud-sdk:latest
  script:
    - docker-compose -f docker-compose.yml build --no-cache deploy
    - docker-compose -f docker-compose.yml push deploy
  only:
    - tags
    - develop

update-demos-sigo:
  stage: triggers
  variables:
    ORIGIN: $ORIGIN
    CI_PIPELINE_ID: $CI_PIPELINE_ID
    PRECURSOR: $CI_PROJECT_NAME
  trigger: zweicom/cl-movistar/sigo/demos-sigo
  only:
    - develop
