version: "3.4"

services:
  deploy:
    image: registryv2.zweicom.com:5000/mcl-otec-webclient:${CI_COMMIT_TAG:-latest}
    build:
      context: .
      dockerfile: docker/deploy/Dockerfile

  testing:
    image: registryv2.zweicom.com:5000/mcl-otec-webclient:${CI_COMMIT_TAG:-latest}-testing
    build:
      context: .
      dockerfile: docker/deploy/Dockerfile

# TESTING
  mcl_test_sigo_db:
    image: registryv2.zweicom.com:5000/mcl-otec-db:latest
    restart: always
    environment:
      TZ: America/Santiago
      MYSQL_DATABASE: OTEC
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: otec_user
      MYSQL_PASSWORD: otec_pass
    command: --event_scheduler=ON --character-set-server=utf8 --collation-server=utf8_unicode_ci
    expose:
      - 3306
  mcl_test_sigo_api:
    image: registryv2.zweicom.com:5000/api-otec:develop
    environment:
      TZ: America/Santiago
      LOG_LEVEL: INFO
      SERVICE_PORT: 4040
      OTEC_DB: root:pass@tcp(mcl_test_sigo_db:3306)/OTEC?charset=utf8&collation=utf8mb4_general_ci&timeout=2s&parseTime=true
      DB_MAXOPENCONNECTIONS: 10
      DB_MAXIDLECONNECTIONS: 5
      DB_PINGINTERVAL: 30
      DB_MAXLIFETIMECONNECTION: 300
      API_SCE_ADDRESS: http://35.192.99.178:2004
    restart: always
    # ports:
    #   - 4040:4040
    expose:
      - 4040
    depends_on:
      - mcl_test_sigo_db
  mcl_test_sigo_web:
    image: registryv2.zweicom.com:5000/mcl-otec-webclient:latest-testing
    environment:
      WEBAPI_NAME: "mcl_test_sigo_api"
      WEBAPI_PORT: "4040"
    expose:
      - 80
    # ports:
    #   - 4003:80
    restart: always
    depends_on:
      - mcl_test_sigo_api

  mcl_e2e_robotframework:
    build:
      context: .
      dockerfile: docker/testing/Dockerfile

# LOCAL
  mcl_local_sigo_api:
    image: registryv2.zweicom.com:5000/api-otec:develop
    environment:
      TZ: America/Santiago
      LOG_LEVEL: INFO
      SERVICE_PORT: 4040
      OTEC_DB: root:pass@tcp(mcl_test_sigo_db:3306)/OTEC?charset=utf8&collation=utf8mb4_general_ci&timeout=2s&parseTime=true
      DB_MAXOPENCONNECTIONS: 10
      DB_MAXIDLECONNECTIONS: 5
      DB_PINGINTERVAL: 30
      DB_MAXLIFETIMECONNECTION: 300
      API_SCE_ADDRESS: http://35.192.99.178:2004
      MOCKUP_PATH: /go/bin/mockups/
    restart: always
    ports: 
      - 4040:4040
    depends_on:
      - mcl_test_sigo_db

  mcl_local_sigo_db:
    image: registryv2.zweicom.com:5000/mcl-otec-db:latest
    restart: always
    environment:
      TZ: America/Santiago
      MYSQL_DATABASE: OTEC
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: otec_user
      MYSQL_PASSWORD: otec_pass
    command: --event_scheduler=ON --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3307:3306
      
  #   MVP
  mvp_otec_db:
    image: registryv2.zweicom.com:5000/mcl-otec-db:mvp-demp
    restart: always
    environment:
      TZ: America/Santiago
      MYSQL_DATABASE: OTEC
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: otec_user
      MYSQL_PASSWORD: otec_pass
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  mvp_api_otec:
    image: registryv2.zweicom.com:5000/api-otec:mvp-demp
    environment:
      TZ: America/Santiago
      LOG_LEVEL: INFO
      SERVICE_PORT: 4040
      OTEC_DB: root:pass@tcp(mvp_otec_db:3306)/OTEC?charset=utf8&collation=utf8mb4_general_ci&timeout=2s&parseTime=true
      DB_MAXOPENCONNECTIONS: 10
      DB_MAXIDLECONNECTIONS: 5
      DB_PINGINTERVAL: 30
      DB_MAXLIFETIMECONNECTION: 300
      API_SCE_ADDRESS: http://35.192.99.178:2004
    restart: always
    expose:
      - 4040
    depends_on:
      - mvp_otec_db
  mvp_otec_web:
    image: registryv2.zweicom.com:5000/mcl-otec-webclient:mvp-demp
    environment:
      WEBAPI_NAME: "mvp_api_otec"
      WEBAPI_PORT: "4040"
    ports:
      - 4200:80
    restart: always
