version: '3.4'

services:
  deploy:
    image: gcr.io/zwcsce/mcl-otec-webclient:${CI_COMMIT_TAG:-latest}
    build:
      context: .
      dockerfile: docker/deploy/Dockerfile

  testing:
    image: gcr.io/zwcsce/mcl-otec-webclient:${CI_COMMIT_TAG:-latest}-testing
    build:
      context: .
      dockerfile: docker/deploy/Dockerfile

  mcl_test_sigo_web:
    build:
      context: .
      dockerfile: docker/deploy_testing/Dockerfile
    environment:
      WEBAPI_NAME: '34.122.92.38'
      WEBAPI_PORT: '4041'
    expose:
      - 80
    container_name: mcl_test_sigo_web
    restart: always

  dockerize-test-waiting:
    image: 'jwilder/dockerize'
    command: >
      -timeout 5m -wait-retry-interval 10s
      -wait tcp://mcl_test_sigo_db:3306

  # LOCAL
  mcl_local_sigo_api:
    image: gcr.io/zwcsce/api-sigo:develop
    environment:
      LDAP_SKIP: '1'
      TZ: America/Santiago
      LOG_LEVEL: DEBUG
      SERVICE_PORT: 4040
      OTEC_DB: root:pass@tcp(mcl_test_sigo_db:3306)/OTEC?charset=utf8&collation=utf8mb4_general_ci&timeout=2s&parseTime=true
      DB_MAXOPENCONNECTIONS: 10
      DB_MAXIDLECONNECTIONS: 5
      DB_PINGINTERVAL: 30
      DB_MAXLIFETIMECONNECTION: 300
      API_SCE_ADDRESS: https://demos-sce.zweicom.services/sce_api
      MOCKUP_PATH: /go/bin/mockups
      TREEOT: mcl_OT
      DEPLOY: test
    restart: always
    ports:
      - 4040:4040
    # depends_on:
    #   - mcl_test_sigo_db

  mcl_local_sigo_db:
    image: gcr.io/zwcsce/mcl-otec-db:latest
    restart: always
    environment:
      TZ: America/Santiago
      MYSQL_DATABASE: OTEC
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: otec_user
      MYSQL_PASSWORD: otec_pass
    command: --event_scheduler=ON --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3307:3306

  # mcl_e2e_robotframework:
  #   build:
  #     context: .
  #     dockerfile: docker/testing/Dockerfile
