version: "3.4"

services:
  deploy:
    image: gcr.io/zwcsce/mcl-otec-webclient:${CI_COMMIT_TAG:-latest}
    build:
      context: .
      dockerfile: docker/deploy/Dockerfile
    environment:
      WEBAPI_NAME: "backend"
      WEBAPI_PORT: "8021"
    ports:
      - 4200:80
    restart: always

  # backend:
  #   image: registryv2.zweicom.com:5000/cloud-webapi:latest
  #   expose:
  #     - 8021
