version: "3.4"

services:
  deploy:
    image: registryv2.zweicom.com:5000/mcl-otec-webclient:${CI_COMMIT_TAG:-latest}
    build:
      context: .
      dockerfile: dockerfiles/deploy/Dockerfile

  develop:
    image: registryv2.zweicom.com:5000/mcl-otec-webclient:${CI_COMMIT_TAG:-latest}-develop
    build:
      context: .
      dockerfile: dockerfiles/deploy/Dockerfile


