import { Component, ViewChild ,OnInit, OnDestroy } from "@angular/core";
import { FormControl, FormGroup } from "@angular/forms";
import { Table } from 'primeng/table';
import { PrimeNGConfig } from 'primeng/api';
import { Subscription } from 'rxjs';
import { ActaFacade } from "@storeOT/acta/acta.facades";
import { keys } from "lodash";
import { NgModule } from "@angular/core";

@Component({
    selector: 'zwc-ots-payment',
    templateUrl: './ots-payment.component.html',
    styleUrls:['./ots-payment.component.scss'],
})
export class OtsPaymentComponent implements OnInit, OnDestroy {
    @ViewChild('dt') table: Table;

    subscription: Subscription = new Subscription();
    imputacion2: any;

    
    integracionData: any[] = [];
    integracionDataColumn: any[] = [];    
    additionData:any;
    selectedActas: any[] = [];

    constructor(private actaFacade: ActaFacade)   { 
        this.actaFacade.getActasImputacion2();
        
        this.additionData = {"acta_estado":"", "usuario":"", "fecha_cont_hem":"", "estado_descripcion":"", "monto_clp":"", "numero_pago":"", "fecha_derivada":"", "estado":"", "numero_cabecera":"", "numero_derivada":"", "tipo_cambio":"", "monto_hem":"", "numero_hem":""};
        this.integracionData = [
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "6",
              "id_acta": "8",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "25",
              "codigo_catalogo": "ServZweicom1",
              "valor_unitario": "20000000.00",
              "cantidad_pagar": "2",
              "valor_pagar": "40000000.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "6",
              "id_acta": "8",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "26",
              "codigo_catalogo": "ServZweicom2",
              "valor_unitario": "10000000.00",
              "cantidad_pagar": "1",
              "valor_pagar": "10000000.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "6",
              "id_acta": "8",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "6",
              "id_acta": "8",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "6",
              "id_acta": "8",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-1",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "CLP",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            },
            {
              "sitio": "",
              "numero_contrato": "3300209195",
              "proveedor": "ZWEICOM S.A.",
              "tipo": "CAPEX",
              "id_pmo": "25",
              "lp": "CHI100",
              "gestor": "Leopoldo Barrios",
              "codigo_sitio": "",
              "pep2": "P-0077-22-2002-05106-021",
              "id_ot": "3",
              "id_acta": "12",
              "nombre": "ordinario_leo_6",
              "aprobador": "Simon Diaz",
              "id_detalle": "-2",
              "codigo_catalogo": "Materiales",
              "valor_unitario": "0.00",
              "cantidad_pagar": "1",
              "valor_pagar": "0.00",
              "valor_total": "50000000.00",
              "moneda": "USD",
              "contrato": "CONTRATO_ORDINARIO",
              "fecha_ingreso": "07-11-2022"
            }
        ];
        
    }

    ngOnInit(): void {        
        this.actaFacade.getActasImputacion2$().subscribe(response => {            
            this.imputacion2 = response?.items;   
            console.log("imputacion2:=", this.imputacion2);         
        });

        this.onAdditionData(this.additionData);
        //console.log("integracionData := ", this.integracionData);
        this.integracionDataColumn = this.onGetKeyFromIntegracionData(this.integracionData?.[0]);                
    }

    onAdditionData(data: object): void {
      this.integracionData = this.integracionData.map((array)=>{
        return {...array, ...data};
      });
    }

    onGetKeyFromIntegracionData(data: object): any[] {      
        const keys = Object.keys(data).reduce((arr, key) => [...arr, {header: key, field: key}], []);
        return keys;
    }

    onDownloadCSV(): void {
    }

    getImputacionData(): void {
      alert("getImputacionData")
    }

    onUploadCsvFile(event:any): void {
      alert("upload csv file");
    }

    onChangeCsvFile(event:any): void {
      alert("load csv file");
    }

    ngOnDestroy(): void {
        this.subscription.unsubscribe();
    }

}