[environment]
    host = 'localhost'
    port = 4206

[users]
    gestor = 'mgestor1'
    supervisor = 'msupervisor1'
    jefearea='mjefearea1'
    subgerente = 'msubgerente1'
    gerente = 'msubgerente1'
    admineecc = 'ccadmincontrato1'
    nombre_admineecc='Luk COBRA CHILE Antonella'
    supervisortrabajos ='cctrabajador1'
    nombre_supervisor_trabajos='Ana COBRA CHILE Antonella'
    operaciones ='moperaciones'

[cubicacion]
    nombre='Cubicacion selenium 3'
    tipo_cubicacion = 'Construcción'
    contrato_marco ='BUCLE'
    agencia='APOQUINDO'
    proveedor ='330000659 - COBRA CHILE SERVICIOS S.A.'
    direccion_desde='los ririos'
    altura_desde='3123'
    direccion_hasta='las castaños'
    altura_hasta='2213'
    detalles='In varius pretium pellentesque. Integer rhoncus sapien eu nisl volutpat fermentum.'
    [[cubicacion.servicios]]
            actividad='MATRIZ'
            tipo_servicio='CABLES'
            nombre='J451'
            cantidad=15
            [[cubicacion.servicios.uos]]
                nombre='D013'
                cantidad=10
            [[cubicacion.servicios.uos]]
                nombre='D012'
                cantidad=14
    [[cubicacion.servicios]]
            actividad='MATRIZ'
            tipo_servicio='LINEAS'
            nombre='J101'
            cantidad=5011
            [[cubicacion.servicios.uos]]
                nombre='C926'
                cantidad='150,37'
            [[cubicacion.servicios.uos]]
                nombre='C881'
                cantidad='2,3'
            [[cubicacion.servicios.uos]]
                nombre='C105'
                cantidad='80,32'
    [[cubicacion.servicios]]
            actividad='FTTX'
            tipo_servicio='PROYECTOS'
            nombre='D080'
            cantidad='1485'
            [[cubicacion.servicios.uos]]
                nombre='0 - SIN UO'
                cantidad=0
    [[cubicacion.servicios]]
            actividad='FIBRA OPTICA'
            tipo_servicio='LINEAS'
            nombre='J201'
            cantidad='10'
            [[cubicacion.servicios.uos]]
                nombre='H006'
                cantidad=9
            [[cubicacion.servicios.uos]]
                nombre='H002'
                cantidad=150
            
[ot]
   nombre='OT selenium 3'
   contrato_marco='BUCLE'
   cubicacion='Cubicacion selenium 3'
   oficina_central='0189 - S.FCO LAS CONDES'
   solicitado_por='ATC'
   direccion='Longitudinal'
   altura='133'
   piso=1
   departamento=13
   comuna='Buin'
   tipo_red='ATP'
   tipo_trabajo='Ampliacion'
   area_negocio='NORMAL'
   nombre_proyectista= 'Andoria algoritmo'
   tipo_sustento='CAPEX'
   pmo=25
   linea_presupuestaria='CHI100'
   pep2='P-0077-22-2002-05106-021'
   admin_contrato="${users['nombre_admineecc']}"

[flujo]
# Puedes comentar, poner en false o quitar la etapa que no quieres que se ejecute
# Solo se ejecutaran las acciones con true
   crear_cubicacion_nueva = true
   crear_ot_nueva=true
   aprobacion_inicial_supervisor = true
#    rechazo_inicial_supervisor = false
   aprobacion_inicial_jefearea = true
#    rechazo_inicial_jefearea = false
#    aprobacion_inicial_subgerente = false
#    rechazo_inicial_subgerente = false
#    aprobacion_inicial_gerente = false
#    rechazo_inicial_gerente = false
   aprobacion_proveedor = true
#    rechazo_proveedor = false
   