nombre_global='Selenium Activos fijos'

[environment]
    host = '34.122.92.38'
    port = 4300
    api_port=4040
    ruta_id_rsa='~/.ssh/id_rsa'

[users]
    gestor = 'zwe257123693'
    supervisor = 'dsupervisor1'
    jefearea='djefearea1'
    subgerente = 'dsubgerente1'
    gerente = 'dgerente1'
    admineecc = 'cobadmincontrato1'
    nombre_admineecc='Tracy Diaz'
    supervisortrabajos ='cobcoordinador1'
    nombre_supervisor_trabajos='Nicolas España'
    operaciones ='doperaciones1'

[cubicacion]
    tipo_cubicacion = 'Construcción'
    contrato_marco ='BUCLE'
    agencia='APOQUINDO'
    proveedor ='330000659 - COBRA CHILE SERVICIOS S.A.'
    direccion_desde='los ririos'
    altura_desde='3123'
    direccion_hasta='las castaños'
    altura_hasta='2213'
    detalles='In varius pretium pellentesque. Integer rhoncus sapien eu nisl volutpat fermentum.'
    [[cubicacion.servicios]]
            actividad='DISTRIBUCION'
            tipo_servicio='LINEAS'
            nombre='J021'
            cantidad=15
            [[cubicacion.servicios.uos]]
                nombre='C213'
                cantidad=10
    [[cubicacion.servicios]]
            actividad='DISTRIBUCION'
            tipo_servicio='LINEAS'
            nombre='J002'
            cantidad=5011
            [[cubicacion.servicios.uos]]
                nombre='C260'
                cantidad='150,37'


[ot]
   contrato_marco='BUCLE'
   oficina_central='0189 - S.FCO LAS CONDES'
   solicitado_por='ATC'
   direccion='Longitudinal'
   altura='133'
   piso=1
   departamento=13
   comuna='Buin'
   tipo_red='ATP'
   tipo_trabajo='Ampliacion'
   area_negocio='NORMAL'
   nombre_proyectista= 'Andoria algoritmo'
   tipo_sustento='CAPEX'
   pmo=25
   linea_presupuestaria='CHI100'
   pep2='P-0077-22-2002-05106-021'

[flujo]
# Puedes comentar poner en false o quitar la etapa que no quieres que se ejecute
# Solo se ejecutaran las acciones con true
    crear_cubicacion_nueva = true
    crear_ot_nueva=true
    aprobacion_inicial_supervisor = true
#    rechazo_inicial_supervisor = false
    aprobacion_inicial_jefearea = true
#    rechazo_inicial_jefearea = false
#    aprobacion_inicial_subgerente = false
#    rechazo_inicial_subgerente = false
#    aprobacion_inicial_gerente = false
#    rechazo_inicial_gerente = false
    aprobacion_proveedor = true
#    rechazo_proveedor = false
    # agregar_adicionales=true
    enviar_informe_avance=true
    aprobar_informe_avance=true
    # rechazar_informe_avance=false
    [[flujo.actas]]
        acta_numero=1
        tipo_pago='TOTAL'
        porcentaje=10
        comentario_generar_acta="""Mauris ac aliquet ipsum. Mauris tincidunt libero quis gravida ultrices. Integer sagittis massa ac augue laoreet placerat. Morbi quis varius eros. Curabitur ornare non purus ut euismod. Aliquam gravida tellus lacus, nec dapibus tellus pretium quis. Vivamus blandit augue vel tortor malesuada tincidunt. Fusce nec nibh metus. Praesent blandit consequat molestie.\
        \
        Fusce efficitur ultrices lacinia. Fusce volutpat laoreet pretium. Nullam tristique odio dui. Nulla massa ipsum, hendrerit non dignissim quis, ullamcorper in nibh. In sodales magna lorem, eget hendrerit ex volutpat nec. Pellentesque hendrerit iaculis ipsum, tristique porta enim. Maecenas sapien metus, ullamcorper eget bibendum non, ultrices in ipsum.\
        """
        comentario_autorizar_pago_supervisor="""Mauris ac aliquet ipsum. Mauris tincidunt libero quis gravida ultrices. Integer sagittis massa ac augue laoreet placerat. Morbi quis varius eros. Curabitur ornare non purus ut euismod. Aliquam gravida tellus lacus, nec dapibus tellus pretium quis. Vivamus blandit augue vel tortor malesuada tincidunt. Fusce nec nibh metus. Praesent blandit consequat molestie.\
        \
        """
        comentario_autorizar_pago_jefearea="""Mauris ac aliquet ipsum. Mauris tincidunt libero quis gravida ultrices. Integer sagittis massa ac augue laoreet placerat. Morbi quis varius eros. Curabitur ornare non purus ut euismod. Aliquam gravida tellus lacus, nec dapibus tellus pretium quis. Vivamus blandit augue vel tortor malesuada tincidunt. Fusce nec nibh metus. Praesent blandit consequat molestie.\
        \
        Fusce efficitur ultrices lacinia. Fusce volutpat laoreet pretium. Nullam tristique odio dui. Nulla massa ipsum, hendrerit non dignissim quis, ullamcorper in nibh. In sodales magna lorem, eget hendrerit ex volutpat nec. Pellentesque hendrerit iaculis ipsum, tristique porta enim. Maecenas sapien metus, ullamcorper eget bibendum non, ultrices in ipsum.
        """
        [[flujo.actas.flujo]]
            generar_acta=true
            aprobar_acta_gestor=true
            # rechazar_acta_gestor=false
            solitar_pago=true
            autorizar_solicitud_pago_supervisor=true
            # rechazar_solicitud_pago_supervisor=false
            autorizar_solicitud_pago_jefearea=true
            # rechazar_solicitud_pago_jefearea=false
            # autorizar_solicitud_pago_subgerente=false
            # rechazar_solicitud_pago_subgerente=false
            # autorizar_solicitud_pago_gerente=false
            # rechazar_solicitud_pago_gerente=false
            imputacion=true
   